### PR TITLE
Add meson profiles

### PR DESCRIPTION
**Pull request by bleakgrey**
This PR adds a `profile` option to the meson configuration. If is set to `development` during compilation, the app will:
- Add `.devel` class to the main window
- Use alternative nightly icon
- Modify About dialog to display branch name and revision hash instead of a version (which makes sense in production builds only)

Additionally, a development Flatpak manifest is added with [Vala SDK](https://github.com/flathub/org.freedesktop.Sdk.Extension.vala) enabled for syntax highlighting in GNOME Builder.

Screenshot from 2023-01-12 11-56-42

### CODE REVIEW

**Comment by bleakgrey** [comment]
We can use this option to disable some debug information in production builds, such as widget destruction logs.

**Comment by GeopJr** [comment]
Looks good to me!

I did the following changes:

- CI should build devel
- Added a check if git is available 
- There was a warning about the missing "check" flag on run_command, so I added it
- And made install.sh build devel

(and merged upstream)

Are there any other profiles that could be added in the future? If not, should devel be a bool instead?

**Comment by bleakgrey** [comment]
I can't think of any other profile, so yeah, a bool makes sense.

**Comment by GeopJr** [comment]
Merging!

**Pull request merged**
