### PR TITLE
workflow: Build for aarch64

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
Related to https://github.com/GeopJr/Tooth/issues/41.

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
I'll be building it in my fork to avoid getting approved. Once done, I'll let you know.

**Comment by GeopJr** [comment]
Looks good to me!

I limited the qemu and docker actions to aarch64 (and bumped the qemu one to v2).
If you still have changes to do, I'll just turn this into a draft until it's ready!

**Comment by TheEvilSkeleton** [comment]
I have no changes to make. But wow, this is unbearably slow :sweat_smile:. I do certainly believe that we should keep it so you can have testers. Of course, it's entirely slow.

**Comment by GeopJr** [comment]
Nothing we can really do I guess, still better than nothing!

Merging, thanks!

**Pull request merged**
